### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by Fivefold** [sjgallagher2/SchematicSymbolsSVG#1]
These look great, thank you for sharing! 

If you want other people to (legally) be able to use them, please add license information. https://choosealicense.com/ can help you choose a license that fits your wishes.

And I don't think you need it but just in case, here is information on how to add license to a github repository https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by sjgallagher2** [comment]
Thanks, added an MIT license
